enable_gui: False
artifacts_dir: ./test/artifacts/
selected_benches:
  - [ turing.ocamllabs.io, ocaml_5.00__5.00, b73cbbea4bc40ffd26a459d594a39b99cec4273d vanilla 20220228_010330 5.00+stable+sequential_1.orun.summary.bench ]
  - [ turing.ocamllabs.io, ocaml_5.00__5.00, f3ea33a4c9b0d2872b0bcccbcce5428b2e468373 vanilla 20220223_010015 5.00+trunk+sequential_1.orun.summary.bench ]
selected_baseline: 5.0.0
